[build]
  command = "npm install && cd nuxt-app && npm ci && npm run generate"
  publish = "nuxt-app/dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"